# -*- coding: utf-8 -*-
"""Electrical Outlets

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V6ooOqvClTd11H_m4EKZ5v_2geqFbzN-
"""

# Success in 0.06s

N = int(input())

for i in range(N):
    values = input().split(' ')
    values = [(int(i)) for i in values][1:]

    outlets = 0
    for val in values:
        outlets += val - 1

    print(outlets + 1)