# -*- coding: utf-8 -*-
"""Hello World!

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V6ooOqvClTd11H_m4EKZ5v_2geqFbzN-
"""

print("Hello World!")