# -*- coding: utf-8 -*-
"""Kornislav

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V6ooOqvClTd11H_m4EKZ5v_2geqFbzN-
"""

a = sorted([int(x) for x in input().split()])
print(a[0]*a[2])